### ISSUE TITLE
Add support for htgroup

### ISSUE THREAD

**Issue by tersmitten** [kkesha/jenkins-htpasswd-auth#1]
[We](https://github.com/Oefenweb) would love to see support for htgroup files. We don't mind helping with the implementation, but need some guidance. Can you specify what needs to be done?

**Comment by tersmitten** [comment]
@kkesha Do you have any suggestion?

**Comment by kkupciunas** [comment]
@tersmitten sorry for really late response, htgroups support is there since v1.1 release (was implemented in b519c8aa38d2b289a522b48d6a9ef245bbea0c34), just haven't updated README.

**Comment by tersmitten** [comment]
I'll have a look at it. Thanks.
